/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import BUS.ChiTietQuyenBUS;
import BUS.NguoiDungBUS;
import DAO.NguoiDungDAO;
import DTO.ChiTietQuyenDTO;
import DTO.NguoiDungDTO;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.SQLException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
/**
 *
 * @author downny
 */
public class CaNhanForm extends javax.swing.JInternalFrame {
    NguoiDungBUS ndBUS = new NguoiDungBUS();
    
    private final ChiTietQuyenBUS ctqBUS = new ChiTietQuyenBUS();
    String taiKhoan;
     private NguoiDungDTO user;

     public CaNhanForm(NguoiDungDTO user) throws SQLException {
        initComponents();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        this.user = user;
        this.taiKhoan = user.getTaiKhoan();
        // Authorization
        // Authorization
        javax.swing.JButton[] buttons = {btnEdit};
        disableAllButtons(buttons);
        authorizeAction(user);
        loadThongTinCaNhan();

    }
    /**
     * Creates new form CaNhanForm
     */
    public CaNhanForm() {
      
       
    }
     private void disableAllButtons(javax.swing.JButton[] buttons) {
        for (javax.swing.JButton btn : buttons) {
            btn.setEnabled(false);
        }
    }
    
    private void authorizeAction(NguoiDungDTO user) {
        // Get all allowed actions in this functionality
        List<ChiTietQuyenDTO> allowedActions = new ArrayList<>();
        try {
            allowedActions = ctqBUS.getAllowedActions(user.getMaNhomQuyen(), "canhan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(CaNhanForm.this, "Lỗi kết nối cơ sở dữ liệu", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(CaNhanForm.this, "Lỗi không xác định", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return;
        }
        
        for (ChiTietQuyenDTO ctq : allowedActions) {
            
            if (ctq.getHanhDong().equals("update")) {
                btnEdit.setEnabled(true);
                continue;
            }
        }
        
    }
    
    private void loadThongTinCaNhan() throws SQLException {
    // Gọi DAO để lấy dữ liệu từ CSDL
    this.user = NguoiDungDAO.getInstance().getInfoByAccount(taiKhoan);
    if (user != null) {
        taiKhoan = user.getTaiKhoan();
        txtHoTen.setText(user.getHoTen());
        txtEmail.setText(user.getEmail());
        if (user.getNgaySinh() != null) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        txtNgaySinh.setText(sdf.format(user.getNgaySinh()));
        } else {
            txtNgaySinh.setText(""); // hoặc "Chưa cập nhật"
        }
        cbbGioiTinh.setSelectedItem(user.getGioiTinh());
        txtDiaChi.setText(user.getDiaChi());
        txtSdt.setText(user.getSdt());
        txtChucVu.setText(user.getTenChucvu());
        txtSoNgayPhep.setText(String.valueOf(user.getSoNgayPhep()));
        txtLuongCB.setText(String.valueOf(user.getLuongCoBan()));
        if (user.getNgayVaoLam() != null) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        txtNgayVaoLam.setText(sdf.format(user.getNgayVaoLam()));
        } else {
            txtNgayVaoLam.setText(""); // hoặc "Chưa cập nhật"
        }
    }
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        lbHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        lbGioiTinh = new javax.swing.JLabel();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        lbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lbChucVu = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        lbSdt = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        lbNgayVaoLam = new javax.swing.JLabel();
        txtNgayVaoLam = new javax.swing.JTextField();
        lbSoNgayPhep = new javax.swing.JLabel();
        txtSoNgayPhep = new javax.swing.JTextField();
        lbLuongCB = new javax.swing.JLabel();
        txtLuongCB = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbInfo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1180, 774));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEdit.setBackground(new java.awt.Color(73, 156, 84));
        btnEdit.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Lưu thay đổi");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 200, 50));

        lbHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbHoTen.setText("Họ tên");
        jPanel4.add(lbHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 70, -1));

        txtHoTen.setEditable(false);
        txtHoTen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtHoTen.setEnabled(false);
        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });
        jPanel4.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 390, 40));

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbEmail.setText("Email");
        jPanel4.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 70, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 390, 40));

        lbNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNgaySinh.setText("Ngày sinh");
        jPanel4.add(lbNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 70, -1));

        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });
        jPanel4.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 390, 40));

        lbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbGioiTinh.setText("Giới tính");
        jPanel4.add(lbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 70, -1));

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbGioiTinh.setSelectedIndex(-1);
        jPanel4.add(cbbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 390, 40));

        lbDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDiaChi.setText("Địa chỉ");
        jPanel4.add(lbDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 70, -1));

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });
        jPanel4.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 390, 40));

        lbChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbChucVu.setText("Chức vụ");
        jPanel4.add(lbChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 70, -1));

        txtChucVu.setEditable(false);
        txtChucVu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtChucVu.setEnabled(false);
        txtChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChucVuActionPerformed(evt);
            }
        });
        jPanel4.add(txtChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 390, 40));

        lbSdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSdt.setText("Số điện thoại");
        jPanel4.add(lbSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 100, -1));

        txtSdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSdtActionPerformed(evt);
            }
        });
        jPanel4.add(txtSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 390, 40));

        lbNgayVaoLam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNgayVaoLam.setText("Ngày vào làm");
        jPanel4.add(lbNgayVaoLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 100, -1));

        txtNgayVaoLam.setEditable(false);
        txtNgayVaoLam.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNgayVaoLam.setEnabled(false);
        txtNgayVaoLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayVaoLamActionPerformed(evt);
            }
        });
        jPanel4.add(txtNgayVaoLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 390, 40));

        lbSoNgayPhep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbSoNgayPhep.setText("Số ngày phép");
        jPanel4.add(lbSoNgayPhep, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 100, -1));

        txtSoNgayPhep.setEditable(false);
        txtSoNgayPhep.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSoNgayPhep.setEnabled(false);
        txtSoNgayPhep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoNgayPhepActionPerformed(evt);
            }
        });
        jPanel4.add(txtSoNgayPhep, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 390, 40));

        lbLuongCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbLuongCB.setText("Lương cơ bản");
        jPanel4.add(lbLuongCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 100, -1));

        txtLuongCB.setEditable(false);
        txtLuongCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuongCBActionPerformed(evt);
            }
        });
        jPanel4.add(txtLuongCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 390, 40));

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 140, 50));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton2.setText("Đổi mật khẩu");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 180, 50));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1180, 650));

        jPanel1.setBackground(new java.awt.Color(73, 156, 84));

        lbInfo.setBackground(new java.awt.Color(255, 255, 255));
        lbInfo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbInfo.setForeground(new java.awt.Color(255, 255, 255));
        lbInfo.setText("THÔNG TIN CÁ NHÂN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(lbInfo)
                .addContainerGap(751, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbInfo)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChucVuActionPerformed

    private void txtSdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSdtActionPerformed

    private void txtNgayVaoLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayVaoLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayVaoLamActionPerformed

    private void txtSoNgayPhepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoNgayPhepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoNgayPhepActionPerformed

    private void txtLuongCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuongCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuongCBActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (user != null) {
        taiKhoan = user.getTaiKhoan();
        txtHoTen.setText(user.getHoTen());
        txtEmail.setText(user.getEmail());
        if (user.getNgaySinh() != null) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        txtNgaySinh.setText(sdf.format(user.getNgaySinh()));
        } else {
            txtNgaySinh.setText(""); // hoặc "Chưa cập nhật"
        }
        cbbGioiTinh.setSelectedItem(user.getGioiTinh());
        txtDiaChi.setText(user.getDiaChi());
        txtSdt.setText(user.getSdt());
        txtChucVu.setText(user.getTenChucvu());
        txtSoNgayPhep.setText(String.valueOf(user.getSoNgayPhep()));
        txtLuongCB.setText(String.valueOf(user.getLuongCoBan()));
        if (user.getNgayVaoLam() != null) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        txtNgayVaoLam.setText(sdf.format(user.getNgayVaoLam()));
        } else {
            txtNgayVaoLam.setText(""); // hoặc "Chưa cập nhật"
        }
    }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        try {
            // Tạo đối tượng NguoiDungDTO
            NguoiDungDTO nd = user;
            String email = txtEmail.getText().trim();
            String ngaySinh = txtNgaySinh.getText().trim();
            String gioiTinh = cbbGioiTinh.getSelectedItem().toString();
            String diaChi = txtDiaChi.getText().trim();
            String sdt = txtSdt.getText().trim();// Giới tính từ ComboBox
            nd.setEmail(email);
            nd.setGioiTinh(gioiTinh);
            nd.setDiaChi(diaChi);
            nd.setSdt(sdt);
            if (email.equals("") || ngaySinh.equals("") || gioiTinh.equals("") || diaChi.equals("") || sdt.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }
            else if(!sdt.matches("\\d{10}") ){
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }
            else if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
                JOptionPane.showMessageDialog(this, "Email không hợp lệ!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }
            else if (!ngaySinh.matches("\\d{2}-\\d{2}-\\d{4}")) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ! Phải theo định dạng dd-mm-yyyy", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }
            else if (NguoiDungDAO.getInstance().hasSDTException(nd)) {
                JOptionPane.showMessageDialog(this, "Số điện thoại bị trùng!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }
            else if (NguoiDungDAO.getInstance().hasEmailException(nd)) {
                JOptionPane.showMessageDialog(this, "Email bị trùng!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, ndBUS.updateCaNhan(nd));
                loadThongTinCaNhan();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
       Window parentWindow = SwingUtilities.getWindowAncestor(this);
        ChangePassword cp = new ChangePassword(parentWindow, true, user);
        cp.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbChucVu;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbLuongCB;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbNgayVaoLam;
    private javax.swing.JLabel lbSdt;
    private javax.swing.JLabel lbSoNgayPhep;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuongCB;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNgayVaoLam;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSoNgayPhep;
    // End of variables declaration//GEN-END:variables
}
