/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.NhanVienBUS;
import BUS.NhomQuyenBUS;
import BUS.TaiKhoanBUS;
import DTO.ChucVuDTO;
import DTO.NguoiDungDTO;
import DTO.NhomQuyenDTO;
import DTO.lsChucVuDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Acer
 */
public class ChangeChucVu extends javax.swing.JFrame {

    /**
     * Creates new form ChangeChucVu
     */
    NhanVienBUS nvBUS = new NhanVienBUS();
    TaiKhoanBUS tkBUS = new TaiKhoanBUS();
    NhomQuyenBUS nqBUS = new NhomQuyenBUS();
    private ArrayList<NhomQuyenDTO> danhSachNhomQuyen = new ArrayList<>();
    private ArrayList<ChucVuDTO> danhSachChucVu = new ArrayList<>();
    private DefaultTableModel tblModel;
    String mataikhoan = "";
    String Chucvubandau;
    private ArrayList<lsChucVuDTO> lsChucVu = new ArrayList<>();
    public ChangeChucVu() {
        initComponents();
    }
    public ChangeChucVu(NguoiDungDTO nv) {
        initComponents();
        initTable();
        // Lưu danh sách chức vụ vào biến toàn cục
        danhSachChucVu = nvBUS.getAllDSChucVu();
        txtLscv.setText(""); // có thể tự sinh
        lsChucVu = nvBUS.getAllLichSuChucVu();
        int maCuoi = lsChucVu.get(lsChucVu.size() - 1).getMals(); 
        int maMoi = maCuoi + 1;
        String mals = String.valueOf(maMoi);
        txtLscv.setText(mals);
        txtLscv.setEditable(false);
        mataikhoan = nv.getTaiKhoan();
        
        nv = nvBUS.getNhanVienByTaiKhoan(mataikhoan);
        
        txtHoten.setText(nv.getHoTen());
        txtHoten.setEditable(false);
        txtLuong.setText(String.valueOf(nv.getLuongCoBan())); 
        txtLuong.setEditable(false);
        // và các thao tác khác tùy ý
        // Load danh sách chức vụ
        ArrayList<ChucVuDTO> listCV = nvBUS.getAllDSChucVu();  // hoặc hàm tương đương
        for (ChucVuDTO cv : listCV) {
            cbxChucVu.addItem(cv.getMaChucVu()+" - "+cv.getTenChucVu());
        }
        // Gán sự kiện chọn chức vụ để cập nhật lương tương ứng
        cbxChucVu.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    int selectedIndex = cbxChucVu.getSelectedIndex();
                    if (selectedIndex >= 0 && selectedIndex < danhSachChucVu.size()) {
                        int luong = danhSachChucVu.get(selectedIndex).getLuongCoBan();
                        txtLuong.removeAll();
                        txtLuong.setText(String.valueOf(luong));
                        txtLuong.setEditable(false);
                    }
                }
            }
        });
        // Set chức vụ hiện tại đang có của nhân viên (nếu cần gợi ý)
        cbxChucVu.setSelectedItem(nv.getMaChucVu()+" - "+nv.getTenChucvu());
        Chucvubandau = nv.getMaChucVu()+"-"+nv.getTenChucvu();
        loadDataToTable(mataikhoan);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    public final void initTable() {
        // Tiêu đề các cột
        String[] headerTbl = new String[]{
            "Mã LSCV", "Họ Tên", "Chức Vụ", "Lương cơ bản", "Ngày thay đổi", "Trạng thái"
        };

        // Tạo model không cho sửa
        tblModel = new DefaultTableModel(null, headerTbl) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblLscv.setModel(tblModel);

        // Căn chỉnh độ rộng cột
        tblLscv.getColumnModel().getColumn(0).setPreferredWidth(1);
        tblLscv.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblLscv.getColumnModel().getColumn(2).setPreferredWidth(200);
        tblLscv.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblLscv.getColumnModel().getColumn(4).setPreferredWidth(70);
        tblLscv.getColumnModel().getColumn(5).setPreferredWidth(30);

        // Căn giữa nội dung bảng
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < tblLscv.getColumnCount(); i++) {
            tblLscv.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Nếu có dữ liệu thì chọn dòng đầu tiên
        if (tblModel.getRowCount() > 0) {
            tblLscv.setRowSelectionInterval(0, 0);
        }
    }
    public void loadDataToTable(String mataikhoan) {
        try {
            ArrayList<lsChucVuDTO> lscv = new ArrayList<lsChucVuDTO>();
            lscv = nvBUS.getLichSuChucVuByTaiKhoan(mataikhoan);
            tblModel.setRowCount(0);
            for (lsChucVuDTO i : lscv) {
                tblModel.addRow(new Object[]{
                    i.getMals(), i.getHoten(), i.getTenchucvu(), i.getLuongcoban(), i.getNgaythaydoi(), i.getTrangthai()
                });
                
            }
            // Auto chọn dòng đầu tiên
            if (tblModel.getRowCount() > 0) {
                tblLscv.setRowSelectionInterval(0, 0);
//                getNhanVienByTaiKhoan();
            }
        } catch (Exception e) {
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTenNCC = new javax.swing.JLabel();
        txtLscv = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        lbDiaChi = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbTenNCC1 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        lbTenNCC2 = new javax.swing.JLabel();
        cbxChucVu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLscv = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTenNCC.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        lbTenNCC.setText("Mã lịch sử chức vụ");
        jPanel1.add(lbTenNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 24));

        txtLscv.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtLscv, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 300, 30));

        txtHoten.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 298, 30));

        lbDiaChi.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        lbDiaChi.setText("Họ tên");
        jPanel1.add(lbDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 50, -1));

        btnLuu.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnLuu.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.setBorder(null);
        btnLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel1.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 140, 38));

        btnHuy.setBackground(new java.awt.Color(255, 0, 51));
        btnHuy.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ");
        btnHuy.setBorder(null);
        btnHuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 140, 38));

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THAY ĐỔI CHỨC VỤ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(286, 286, 286))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 70));

        lbTenNCC1.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        lbTenNCC1.setText("Chức vụ thay đổi ");
        jPanel1.add(lbTenNCC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, 24));

        txtLuong.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
        jPanel1.add(txtLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 300, 30));

        lbTenNCC2.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        lbTenNCC2.setText("Lương cơ bản");
        jPanel1.add(lbTenNCC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, 24));

        jPanel1.add(cbxChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 300, 30));

        tblLscv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã lscv", "Họ tên", "Chức vụ", "Lương cơ bản", "Ngày thay đổi"
            }
        ));
        jScrollPane1.setViewportView(tblLscv);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 810, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        
        String Chucvuhientai = (String) cbxChucVu.getSelectedItem();
        if (!Chucvuhientai.equals(Chucvubandau)) {
            int malscv = Integer.valueOf(txtLscv.getText());
            String taikhoan = mataikhoan;
            String hoten = txtHoten.getText();
            int luong = Integer.valueOf(txtLuong.getText());
            String Chucvu = (String) cbxChucVu.getSelectedItem();
            String[] parts = Chucvu.split(" - ");
            int maChucVu = Integer.parseInt(parts[0]);
            String tenchucvu = parts[1];
            LocalDate Ngaythaydoi = LocalDate.now();
            Date ngayThayDoiDate = Date.from(Ngaythaydoi.atStartOfDay(ZoneId.systemDefault()).toInstant());
            int Trangthai = 1;
            
            danhSachNhomQuyen = nqBUS.getAllDSNhomQuyen();
            
            int manhomquyen = -1; // Khởi tạo giá trị mặc định
            for (NhomQuyenDTO i : danhSachNhomQuyen) {
                if (i.getTenNhomQuyen().equals(tenchucvu)) {
                    manhomquyen = i.getMaNhomQuyen();
                    break; // Thoát vòng lặp khi tìm thấy
                }
            }

            if (manhomquyen == -1) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhóm quyền phù hợp với chức vụ");
                return; // Không tiếp tục nếu không có nhóm quyền phù hợp
            }
            lsChucVuDTO lscv = new lsChucVuDTO(malscv, taikhoan, hoten, maChucVu, tenchucvu, ngayThayDoiDate, luong, Trangthai);

            boolean result = nvBUS.capNhatChucVuNguoiDung(mataikhoan, maChucVu, tenchucvu, manhomquyen, ngayThayDoiDate, lscv);
            if (result) {
                JOptionPane.showMessageDialog(this, "Thay đổi chức vụ thành công");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Thay đổi thất bại");
            }
            
        }else {
            JOptionPane.showMessageDialog(this, "Chức vụ không thay đổi");
            dispose();
        }
        
        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeChucVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cbxChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbTenNCC;
    private javax.swing.JLabel lbTenNCC1;
    private javax.swing.JLabel lbTenNCC2;
    private javax.swing.JTable tblLscv;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtLscv;
    private javax.swing.JTextField txtLuong;
    // End of variables declaration//GEN-END:variables
}
