/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import BUS.ChucVuBUS;
import BUS.NguoiDungBUS;
import DAO.NguoiDungDAO;
import DTO.ChucVuDTO;
import DTO.NguoiDungDTO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author downny
 */
public class UpdateNhanVien extends javax.swing.JDialog {

    /**
     * Creates new form UpdateNhanVien
     */
    private ArrayList<ChucVuDTO> dsChucVu;
    private NhanVienForm parent;
    NguoiDungBUS ndBUS = new NguoiDungBUS();
    public UpdateNhanVien(javax.swing.JInternalFrame parent,javax.swing.JFrame owner, boolean modal) {
        super(owner, modal);
        this.parent = (NhanVienForm) parent;
        initComponents();
       
        setLocationRelativeTo(null);
        
        // Bước 1: Lấy danh sách chức vụ
        dsChucVu = new ChucVuBUS().getAllDanhSachChucVu();

        // Bước 2: Load dữ liệu vào combobox
        loadChucVuToComboBox();

        // Bước 3: Gắn sự kiện sau khi dữ liệu đã load
        cbbChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int selectedIndex = cbbChucVu.getSelectedIndex();
                if (selectedIndex >= 0 && selectedIndex < dsChucVu.size()) {
                    int luong = dsChucVu.get(selectedIndex).getLuongCoBan();
                    txtLuongCB.setText(String.valueOf(luong));
                }
            }
        });
        
        // Bước 4: Hiển thị thông tin nhân viên đang chỉnh sửa
        displayInfo();
    }
    private UpdateNhanVien(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void displayInfo() {
        NguoiDungDTO nv = parent.getNhanVienSelect();
        if (nv != null) {
            // Hiển thị họ tên
            txtHoten.setText(nv.getHoTen());

            // Hiển thị chức vụ
            for (int i = 0; i < dsChucVu.size(); i++) {
                if (dsChucVu.get(i).getMaChucVu() == nv.getMaChucVu()) {
                    cbbChucVu.setSelectedIndex(i);
                    break;
                }
            }

            // Hiển thị lương hiện tại của nhân viên
            txtLuongCB.setText(String.valueOf(nv.getLuongCoBan()));
        }
    }

    
    private void loadChucVuToComboBox() {
        cbbChucVu.removeAllItems();
        for (ChucVuDTO chucVu : dsChucVu) {
            cbbChucVu.addItem(chucVu.getTenChucVu());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbHoten = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        lbChucVu = new javax.swing.JLabel();
        cbbChucVu = new javax.swing.JComboBox<>();
        txtLuongCB = new javax.swing.JTextField();
        lbLuongCB = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbHoten.setText("Họ tên:");
        jPanel1.add(lbHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, -1));

        txtHoten.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtHoten.setEnabled(false);
        jPanel1.add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 298, 50));

        lbChucVu.setText("Chức vụ:");
        jPanel1.add(lbChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 24));

        cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý kho", "Quản lý nhân sự", "Quản lý kinh doanh", "Nhân viên nhập kho", "Nhân viên xuất kho" }));
        jPanel1.add(cbbChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 300, 50));

        txtLuongCB.setEditable(false);
        txtLuongCB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLuongCB.setEnabled(false);
        jPanel1.add(txtLuongCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 348, 298, 50));

        lbLuongCB.setText("Lương cơ bản:");
        jPanel1.add(lbLuongCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, -1));

        btnLuu.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.setBorder(null);
        btnLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel1.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 140, 38));

        btnHuy.setBackground(new java.awt.Color(255, 0, 51));
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ");
        btnHuy.setBorder(null);
        btnHuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 140, 38));

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CẬP NHẬT THÔNG TIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
         NguoiDungDTO nv = parent.getNhanVienSelect(); // Lấy NV đang chỉnh sửa

        int selectedIndex = cbbChucVu.getSelectedIndex();
        if (selectedIndex >= 0 && selectedIndex < dsChucVu.size()) {
            int maChucVu = dsChucVu.get(selectedIndex).getMaChucVu();
            int luongMoi = dsChucVu.get(selectedIndex).getLuongCoBan();

            nv.setMaChucVu(maChucVu); // Gán lại mã chức vụ mới cho nhân viên
            nv.setLuongCoBan(luongMoi); // Gán lại lương theo chức vụ mới
        }

        String result = ndBUS.updateChucVuNhanVien(nv);
        JOptionPane.showMessageDialog(this, result);

        if (result.equals("Cập nhật thành công!")) {
            parent.loadDataToTable(); // Load lại dữ liệu trong bảng
            this.dispose(); // Đóng dialog sau khi cập nhật
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateNhanVien dialog = new UpdateNhanVien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbChucVu;
    private javax.swing.JLabel lbHoten;
    private javax.swing.JLabel lbLuongCB;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtLuongCB;
    // End of variables declaration//GEN-END:variables
}
